
CREATE TABLE public.DIM_TIEMPO (
                SK_TIEMPO INTEGER NOT NULL,
                ANIO INTEGER NOT NULL,
                SEMESTRE INTEGER NOT NULL,
                NOMBRE_SEMESTRE VARCHAR(20) NOT NULL,
                TRIMESTRE INTEGER NOT NULL,
                NOMBRE_TRIMESTRE VARCHAR(20) NOT NULL,
                MES INTEGER NOT NULL,
                NOMBRE_MES VARCHAR(20) NOT NULL,
                DIA INTEGER NOT NULL,
                FECHA DATE NOT NULL,
                CONSTRAINT dim_tiempo_pk PRIMARY KEY (SK_TIEMPO)
);


CREATE TABLE public.DIM_UBICACION (
                SK_UBICACION INTEGER NOT NULL,
                PK_UBICACION INTEGER NOT NULL,
                PK_PROVINCIA INTEGER NOT NULL,
                PROVINCIA VARCHAR(50) NOT NULL,
                PK_CANTON INTEGER NOT NULL,
                CANTON VARCHAR(50) NOT NULL,
                PK_AREA INTEGER NOT NULL,
                AREA VARCHAR(50) NOT NULL,
                VALIDO_DESDE DATE,
                VALIDO_HASTA DATE,
                VERSION INTEGER NOT NULL,
                CONSTRAINT dim_ubicacion_pk PRIMARY KEY (SK_UBICACION)
);


CREATE TABLE public.DIM_ESTABLECIMIENTO (
                SK_ESTABLECIMIENTO INTEGER NOT NULL,
                PK_ESTABLECIMIENTO INTEGER NOT NULL,
                PK_ENTIDAD INTEGER NOT NULL,
                ENTIDAD_ESTABLECIMIENTO VARCHAR(50) NOT NULL,
                PK_SECTOR INTEGER NOT NULL,
                SECTOR_ESTABLECIMIENTO VARCHAR(50) NOT NULL,
                PK_TIPO INTEGER NOT NULL,
                TIPO_ESTABLECIMIENTO VARCHAR(50) NOT NULL,
                PK_CLASE INTEGER NOT NULL,
                CLASE_ESTABLECIMIENTO VARCHAR(50) NOT NULL,
                VALIDO_DESDE DATE,
                VALIDO_HASTA DATE,
                VERSION INTEGER NOT NULL,
                CONSTRAINT dim_establecimiento_pk PRIMARY KEY (SK_ESTABLECIMIENTO)
);


CREATE TABLE public.FACT_CAMAS (
                SK_UBICACION INTEGER NOT NULL,
                SK_TIEMPO INTEGER NOT NULL,
                SK_ESTABLECIMIENTO INTEGER NOT NULL,
                TOTAL_DOTACION_CAMAS INTEGER NOT NULL,
                TOTAL_CAMAS_DISPONIBLES INTEGER NOT NULL,
                CAMAS_CIUDADANOS_INTERMEDIOS INTEGER NOT NULL,
                CAMAS_EMERGENCIA INTEGER NOT NULL,
                DIAS_CAMA_DISPONIBLES INTEGER NOT NULL,
                CAMAS_CIUDADANOS_INTENSIVOS INTEGER NOT NULL,
                CAMAS_OTROS_SERVICIOS_APOYO INTEGER NOT NULL,
                CONSTRAINT fact_camas_pk PRIMARY KEY (SK_UBICACION, SK_TIEMPO, SK_ESTABLECIMIENTO)
);


ALTER TABLE public.FACT_CAMAS ADD CONSTRAINT dim_tiempo_fact_camas_fk
FOREIGN KEY (SK_TIEMPO)
REFERENCES public.DIM_TIEMPO (SK_TIEMPO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.FACT_CAMAS ADD CONSTRAINT dim_ubicacion_fact_camas_fk
FOREIGN KEY (SK_UBICACION)
REFERENCES public.DIM_UBICACION (SK_UBICACION)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;

ALTER TABLE public.FACT_CAMAS ADD CONSTRAINT dim_clase_fact_camas_fk
FOREIGN KEY (SK_ESTABLECIMIENTO)
REFERENCES public.DIM_ESTABLECIMIENTO (SK_ESTABLECIMIENTO)
ON DELETE NO ACTION
ON UPDATE NO ACTION
NOT DEFERRABLE;
